/* linux/arch/arm/mach-exynos4/include/mach/gpio.h
 *
 * Copyright (c) 2010-2011 Samsung Electronics Co., Ltd.
 *		http://www.samsung.com
 *
 * EXYNOS4 - GPIO lib support
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
*/

#ifndef __ASM_ARCH_GPIO_H
#define __ASM_ARCH_GPIO_H __FILE__

/* Practically, GPIO banks up to GPZ are the configurable gpio banks */

/* GPIO bank sizes */
#define EXYNOS4_GPIO_A0_NR	(8)
#define EXYNOS4_GPIO_A1_NR	(6)
#define EXYNOS4_GPIO_B_NR	(8)
#define EXYNOS4_GPIO_C0_NR	(5)
#define EXYNOS4_GPIO_C1_NR	(5)
#define EXYNOS4_GPIO_D0_NR	(4)
#define EXYNOS4_GPIO_D1_NR	(4)
#define EXYNOS4_GPIO_E0_NR	(5)
#define EXYNOS4_GPIO_E1_NR	(8)
#define EXYNOS4_GPIO_E2_NR	(6)
#define EXYNOS4_GPIO_E3_NR	(8)
#define EXYNOS4_GPIO_E4_NR	(8)
#define EXYNOS4_GPIO_F0_NR	(8)
#define EXYNOS4_GPIO_F1_NR	(8)
#define EXYNOS4_GPIO_F2_NR	(8)
#define EXYNOS4_GPIO_F3_NR	(6)
#define EXYNOS4_GPIO_J0_NR	(8)
#define EXYNOS4_GPIO_J1_NR	(5)
#define EXYNOS4_GPIO_K0_NR	(7)
#define EXYNOS4_GPIO_K1_NR	(7)
#define EXYNOS4_GPIO_K2_NR	(7)
#define EXYNOS4_GPIO_K3_NR	(7)
#define EXYNOS4_GPIO_L0_NR	(8)
#define EXYNOS4_GPIO_L1_NR	(3)
#define EXYNOS4_GPIO_L2_NR	(8)
#define EXYNOS4_GPIO_X0_NR	(8)
#define EXYNOS4_GPIO_X1_NR	(8)
#define EXYNOS4_GPIO_X2_NR	(8)
#define EXYNOS4_GPIO_X3_NR	(8)
#define EXYNOS4_GPIO_Y0_NR	(6)
#define EXYNOS4_GPIO_Y1_NR	(4)
#define EXYNOS4_GPIO_Y2_NR	(6)
#define EXYNOS4_GPIO_Y3_NR	(8)
#define EXYNOS4_GPIO_Y4_NR	(8)
#define EXYNOS4_GPIO_Y5_NR	(8)
#define EXYNOS4_GPIO_Y6_NR	(8)
#define EXYNOS4_GPIO_Z_NR	(7)

/* GPIO bank numbers */

#define EXYNOS4_GPIO_NEXT(__gpio) \
	((__gpio##_START) + (__gpio##_NR) + CONFIG_S3C_GPIO_SPACE + 1)

enum s5p_gpio_number {
	EXYNOS4_GPIO_A0_START	= 0,
	EXYNOS4_GPIO_A1_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_A0),
	EXYNOS4_GPIO_B_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_A1),
	EXYNOS4_GPIO_C0_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_B),
	EXYNOS4_GPIO_C1_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_C0),
	EXYNOS4_GPIO_D0_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_C1),
	EXYNOS4_GPIO_D1_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_D0),
	EXYNOS4_GPIO_E0_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_D1),
	EXYNOS4_GPIO_E1_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_E0),
	EXYNOS4_GPIO_E2_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_E1),
	EXYNOS4_GPIO_E3_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_E2),
	EXYNOS4_GPIO_E4_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_E3),
	EXYNOS4_GPIO_F0_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_E4),
	EXYNOS4_GPIO_F1_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_F0),
	EXYNOS4_GPIO_F2_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_F1),
	EXYNOS4_GPIO_F3_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_F2),
	EXYNOS4_GPIO_J0_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_F3),
	EXYNOS4_GPIO_J1_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_J0),
	EXYNOS4_GPIO_K0_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_J1),
	EXYNOS4_GPIO_K1_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_K0),
	EXYNOS4_GPIO_K2_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_K1),
	EXYNOS4_GPIO_K3_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_K2),
	EXYNOS4_GPIO_L0_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_K3),
	EXYNOS4_GPIO_L1_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_L0),
	EXYNOS4_GPIO_L2_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_L1),
	EXYNOS4_GPIO_X0_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_L2),
	EXYNOS4_GPIO_X1_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_X0),
	EXYNOS4_GPIO_X2_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_X1),
	EXYNOS4_GPIO_X3_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_X2),
	EXYNOS4_GPIO_Y0_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_X3),
	EXYNOS4_GPIO_Y1_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_Y0),
	EXYNOS4_GPIO_Y2_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_Y1),
	EXYNOS4_GPIO_Y3_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_Y2),
	EXYNOS4_GPIO_Y4_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_Y3),
	EXYNOS4_GPIO_Y5_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_Y4),
	EXYNOS4_GPIO_Y6_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_Y5),
	EXYNOS4_GPIO_Z_START	= EXYNOS4_GPIO_NEXT(EXYNOS4_GPIO_Y6),
};

/* EXYNOS4 GPIO number definitions */
#define EXYNOS4_GPA0(_nr)	(EXYNOS4_GPIO_A0_START + (_nr))
#define EXYNOS4_GPA1(_nr)	(EXYNOS4_GPIO_A1_START + (_nr))
#define EXYNOS4_GPB(_nr)	(EXYNOS4_GPIO_B_START + (_nr))
#define EXYNOS4_GPC0(_nr)	(EXYNOS4_GPIO_C0_START + (_nr))
#define EXYNOS4_GPC1(_nr)	(EXYNOS4_GPIO_C1_START + (_nr))
#define EXYNOS4_GPD0(_nr)	(EXYNOS4_GPIO_D0_START + (_nr))
#define EXYNOS4_GPD1(_nr)	(EXYNOS4_GPIO_D1_START + (_nr))
#define EXYNOS4_GPE0(_nr)	(EXYNOS4_GPIO_E0_START + (_nr))
#define EXYNOS4_GPE1(_nr)	(EXYNOS4_GPIO_E1_START + (_nr))
#define EXYNOS4_GPE2(_nr)	(EXYNOS4_GPIO_E2_START + (_nr))
#define EXYNOS4_GPE3(_nr)	(EXYNOS4_GPIO_E3_START + (_nr))
#define EXYNOS4_GPE4(_nr)	(EXYNOS4_GPIO_E4_START + (_nr))
#define EXYNOS4_GPF0(_nr)	(EXYNOS4_GPIO_F0_START + (_nr))
#define EXYNOS4_GPF1(_nr)	(EXYNOS4_GPIO_F1_START + (_nr))
#define EXYNOS4_GPF2(_nr)	(EXYNOS4_GPIO_F2_START + (_nr))
#define EXYNOS4_GPF3(_nr)	(EXYNOS4_GPIO_F3_START + (_nr))
#define EXYNOS4_GPJ0(_nr)	(EXYNOS4_GPIO_J0_START + (_nr))
#define EXYNOS4_GPJ1(_nr)	(EXYNOS4_GPIO_J1_START + (_nr))
#define EXYNOS4_GPK0(_nr)	(EXYNOS4_GPIO_K0_START + (_nr))
#define EXYNOS4_GPK1(_nr)	(EXYNOS4_GPIO_K1_START + (_nr))
#define EXYNOS4_GPK2(_nr)	(EXYNOS4_GPIO_K2_START + (_nr))
#define EXYNOS4_GPK3(_nr)	(EXYNOS4_GPIO_K3_START + (_nr))
#define EXYNOS4_GPL0(_nr)	(EXYNOS4_GPIO_L0_START + (_nr))
#define EXYNOS4_GPL1(_nr)	(EXYNOS4_GPIO_L1_START + (_nr))
#define EXYNOS4_GPL2(_nr)	(EXYNOS4_GPIO_L2_START + (_nr))
#define EXYNOS4_GPX0(_nr)	(EXYNOS4_GPIO_X0_START + (_nr))
#define EXYNOS4_GPX1(_nr)	(EXYNOS4_GPIO_X1_START + (_nr))
#define EXYNOS4_GPX2(_nr)	(EXYNOS4_GPIO_X2_START + (_nr))
#define EXYNOS4_GPX3(_nr)	(EXYNOS4_GPIO_X3_START + (_nr))
#define EXYNOS4_GPY0(_nr)	(EXYNOS4_GPIO_Y0_START + (_nr))
#define EXYNOS4_GPY1(_nr)	(EXYNOS4_GPIO_Y1_START + (_nr))
#define EXYNOS4_GPY2(_nr)	(EXYNOS4_GPIO_Y2_START + (_nr))
#define EXYNOS4_GPY3(_nr)	(EXYNOS4_GPIO_Y3_START + (_nr))
#define EXYNOS4_GPY4(_nr)	(EXYNOS4_GPIO_Y4_START + (_nr))
#define EXYNOS4_GPY5(_nr)	(EXYNOS4_GPIO_Y5_START + (_nr))
#define EXYNOS4_GPY6(_nr)	(EXYNOS4_GPIO_Y6_START + (_nr))
#define EXYNOS4_GPZ(_nr)	(EXYNOS4_GPIO_Z_START + (_nr))

/* the end of the EXYNOS4 specific gpios */
#define EXYNOS4_GPIO_END	(EXYNOS4_GPZ(EXYNOS4_GPIO_Z_NR) + 1)
#define S3C_GPIO_END		EXYNOS4_GPIO_END

/* define the number of gpios we need to the one after the GPZ() range */
#define ARCH_NR_GPIOS		(EXYNOS4_GPZ(EXYNOS4_GPIO_Z_NR) +	\
				 CONFIG_SAMSUNG_GPIO_EXTRA + 1)

//these gpio definitions are for i9100 rev02
//other revisions and boards (i.e., Galaxy Note) will need fixups

#define	GPIO_XMMC0_CDn	EXYNOS4_GPK0(2)

#define	GPIO_PS_ALS_SDA	EXYNOS4_GPK2(2)
#define	GPIO_PS_ALS_SCL	EXYNOS4_GPK3(2)

#define	GPIO_GYRO_INT	EXYNOS4_GPX0(0)
#define	GPIO_GYRO_FIFOP_INT	EXYNOS4_GPX0(1)
#define	GPIO_PS_ALS_INT	EXYNOS4_GPX0(2)

#define	GPIO_BUCK1_EN_A	EXYNOS4_GPX0(5)
#define	GPIO_BUCK1_EN_B	EXYNOS4_GPX0(6)
#define	GPIO_BUCK2_EN	EXYNOS4_GPL0(0)
#define	GPIO_PMIC_IRQ	EXYNOS4_GPX0(7)

#define	GPIO_VOL_UP	EXYNOS4_GPX2(0)
#define	GPIO_VOL_DOWN	EXYNOS4_GPX2(1)
#define	GPIO_nPOWER	EXYNOS4_GPX2(7)
#define	GPIO_OK_KEY	EXYNOS4_GPX3(5)

#define	VT_CAM_SDA_18V	EXYNOS4_GPC1(0)
#define	VT_CAM_SCL_18V	EXYNOS4_GPC1(2)

#define	CODEC_VT_SDA_18V	EXYNOS4_GPC1(3)
#define	CODEC_VT_SCL_18V	EXYNOS4_GPC1(4)

#define	GPIO_ISP_RESET	EXYNOS4_GPY3(7)
#define	GPIO_FUEL_SDA	EXYNOS4_GPY4(0)
#define	GPIO_FUEL_SCL	EXYNOS4_GPY4(1)
#define	GPIO_FUEL_ALERT	EXYNOS4_GPX2(3)

#define	GPIO_USB_SDA	EXYNOS4_GPE1(0)
#define	GPIO_USB_SCL	EXYNOS4_GPE1(1)
#define	GPIO_MASSMEM_EN	EXYNOS4_GPL1(1)
#define	GPIO_MASSMEM_EN_LEVEL	0

#define	GPIO_TSP_INT	EXYNOS4_GPX0(4)
#define	GPIO_TSP_LDO_ON	EXYNOS4_GPL0(3)

#define	GPIO_CAM_IO_EN	EXYNOS4_GPE2(1)
#define	GPIO_CAM_SENSOR_CORE	EXYNOS4_GPE2(5)
#define	GPIO_8M_AF_EN	EXYNOS4_GPK1(1)
#define GPIO_CAM_8M_ISP_INT	EXYNOS4_GPX1(5)

#define	GPIO_USB_SEL	EXYNOS4_GPL0(6)
#define	GPIO_UART_SEL	EXYNOS4_GPY4(7)

#define	GPIO_3_TOUCH_SCL	EXYNOS4_GPK1(0)
#define	GPIO_3_TOUCH_SDA	EXYNOS4_GPK1(2)
#define	GPIO_3_TOUCH_INT	EXYNOS4_GPL0(5)

#define	GPIO_VT_CAM_15V	EXYNOS4_GPE2(2)

#define	GPIO_CAM_MCLK	EXYNOS4_GPJ1(3)

#define	GPIO_CAM_VGA_nSTBY	EXYNOS4_GPL2(0)
#define	GPIO_CAM_VGA_nRST	EXYNOS4_GPL2(1)

#define	GPIO_DET_35	EXYNOS4_GPX3(2)
#define	GPIO_DET_35_AF	0xF

#define	GPIO_EAR_SEND_END	EXYNOS4_GPX3(6)
#define	GPIO_EAR_SEND_END_AF	0xF

#define	GPIO_GPS_PWR_EN	EXYNOS4_GPE0(3)
#define	GPIO_GPS_nRST	EXYNOS4_GPE0(4)

#define	GPIO_BT_RXD	EXYNOS4_GPA0(0)
#define	GPIO_BT_RXD_AF	2

#define	GPIO_BT_TXD	EXYNOS4_GPA0(1)
#define	GPIO_BT_TXD_AF	2

#define	GPIO_BT_CTS	EXYNOS4_GPA0(2)
#define	GPIO_BT_CTS_AF	2

#define	GPIO_BT_RTS	EXYNOS4_GPA0(3)
#define	GPIO_BT_RTS_AF	2

#define	GPIO_GPS_RXD	EXYNOS4_GPA0(4)
#define	GPIO_GPS_RXD_AF	2

#define	GPIO_GPS_TXD	EXYNOS4_GPA0(5)
#define	GPIO_GPS_TXD_AF	2

#define	GPIO_GPS_CTS	EXYNOS4_GPA0(6)
#define	GPIO_GPS_CTS_AF	2

#define	GPIO_GPS_RTS	EXYNOS4_GPA0(7)
#define	GPIO_GPS_RTS_AF	2

#define	GPIO_NFC_SCL	EXYNOS4_GPY0(0)
#define	GPIO_NFC_SDA	EXYNOS4_GPY0(1)
#define	GPIO_NFC_EN	EXYNOS4_GPL2(6)
#define	GPIO_NFC_FIRM	EXYNOS4_GPL2(7)
#define	GPIO_NFC_IRQ	EXYNOS4_GPX1(7)

#define	GPIO_2MIC_PWDN	EXYNOS4_GPL2(3)
#define	GPIO_2MIC_RST	EXYNOS4_GPL2(4)
#define	GPIO_2MIC_EN	EXYNOS4_GPL2(5)

#define	GPIO_CHG_EN	EXYNOS4_GPL2(2)
#define	GPIO_CHG_ING_N	EXYNOS4_GPL2(4)
#define	GPIO_TA_nCONNECTED	EXYNOS4_GPL2(5)

#define	GPIO_2MIC_SDA	EXYNOS4_GPC1(2)
#define	GPIO_2MIC_SCL	EXYNOS4_GPC1(0)

#define	GPIO_FLM_RXD	EXYNOS4_GPA1(4)
#define	GPIO_FLM_TXD	EXYNOS4_GPA1(5)

#define	GPIO_PHONE_ON	EXYNOS4_GPC1(1)
#define	GPIO_PHONE_ACTIVE	EXYNOS4_GPX1(6)
#define	GPIO_PDA_ACTIVE	EXYNOS4_GPY4(2)
#define	GPIO_CP_DUMP_INT	EXYNOS4_GPX1(2)
#define	GPIO_CP_RST	EXYNOS4_GPX1(4)
#define	GPIO_CP_REQ_RESET	EXYNOS4_GPY4(6)
#define	GPIO_IPC_SLAVE_WAKEUP	EXYNOS4_GPX1(0)
#define	GPIO_IPC_HOST_WAKEUP	EXYNOS4_GPX1(1)
#define	GPIO_SUSPEND_REQUEST	EXYNOS4_GPX1(3)
#define	GPIO_ISP_INT	EXYNOS4_GPX1(5)
#define	GPIO_ACTIVE_STATE	EXYNOS4_GPY3(5)

#define	IRQ_PHONE_ACTIVE	IRQ_EINT14
#define	IRQ_SUSPEND_REQUEST	IRQ_EINT11
#define	IRQ_IPC_HOST_WAKEUP	IRQ_EINT9

#define	GPIO_WLAN_EN	EXYNOS4_GPL1(2)
#define	GPIO_WLAN_EN_AF	1

#define	GPIO_BT_EN	EXYNOS4_GPL0(4)
#define	GPIO_BT_nRST	EXYNOS4_GPL1(0)

#define	GPIO_WLAN_HOST_WAKE	EXYNOS4_GPX2(5)
#define	GPIO_WLAN_HOST_WAKE_AF	0xF

#define	GPIO_BT_HOST_WAKE	EXYNOS4_GPX2(6)
#define	GPIO_BT_HOST_WAKE_AF	0xF

#define	GPIO_BT_WAKE	EXYNOS4_GPX3(1)

#define	GPIO_WLAN_SDIO_CLK	EXYNOS4_GPK3(0)
#define	GPIO_WLAN_SDIO_CLK_AF	2

#define	GPIO_WLAN_SDIO_CMD	EXYNOS4_GPK3(1)
#define	GPIO_WLAN_SDIO_CMD_AF	2

#define	GPIO_WLAN_SDIO_D0	EXYNOS4_GPK3(3)
#define	GPIO_WLAN_SDIO_D0_AF	2

#define	GPIO_WLAN_SDIO_D1	EXYNOS4_GPK3(4)
#define	GPIO_WLAN_SDIO_D1_AF	2

#define	GPIO_WLAN_SDIO_D2	EXYNOS4_GPK3(5)
#define	GPIO_WLAN_SDIO_D2_AF	2

#define	GPIO_WLAN_SDIO_D3	EXYNOS4_GPK3(6)
#define	GPIO_WLAN_SDIO_D3_AF	2

#define	GPIO_HW_REV0	EXYNOS4_GPE1(0)
#define	GPIO_HW_REV1	EXYNOS4_GPE1(1)
#define	GPIO_HW_REV2	EXYNOS4_GPE1(2)
#define	GPIO_HW_REV3	EXYNOS4_GPE1(3)

#define	GPIO_MHL_RST	EXYNOS4_GPF3(4)
#define	GPIO_MHL_INT	EXYNOS4_GPF3(5)
#define	GPIO_MHL_INT_AF	S3C_GPIO_SFN(0xF)
#define	GPIO_MHL_WAKE_UP	EXYNOS4_GPJ1(4)
#define	GPIO_MHL_WAKE_UP_AF	S3C_GPIO_SFN(0xF)
#define	GPIO_MHL_SEL	EXYNOS4_GPL0(1)

#define	GPIO_BOOT_MODE	EXYNOS4_GPX0(3)

#define	GPIO_MSENSE_INT	EXYNOS4_GPX2(2)
#define	GPIO_HDMI_EN	EXYNOS4_GPX2(4)
#define	GPIO_HDMI_EN_REV07	EXYNOS4_GPL1(1)
#define	GPIO_ACC_INT	EXYNOS4_GPX3(0)
#define	GPIO_USB_OTG_EN	EXYNOS4_GPX3(3)
#define	GPIO_HSMMC2_CD	EXYNOS4_GPX3(4)

#define	GPIO_MHL_SDA_28V	EXYNOS4_GPD0(2)
#define	GPIO_MHL_SDA_AF	0x3
#define	GPIO_MHL_SCL_28V	EXYNOS4_GPD0(3)
#define	GPIO_MHL_SCL_AF	0x3
#define	GPIO_MHL_SDA_18V	EXYNOS4_GPY3(0)
#define	GPIO_MHL_SCL_18V	EXYNOS4_GPY3(2)

#define	SMDK4210_SPI_LCD_BUS	3
#define	GPIO_LCD_SPI_SCK	EXYNOS4_GPY3(1)
#define	GPIO_LCD_SPI_MOSI	EXYNOS4_GPY3(3)
#define	GPIO_LCD_SPI_CS	EXYNOS4_GPY4(3)
#define GPIO_LCD_RESET	EXYNOS4_GPY4(5)

//#define	MHL_INT_IRQ	gpio_to_irq(GPIO_MHL_INT)
//#define	MHL_WAKEUP_IRQ	gpio_to_irq(GPIO_MHL_WAKE_UP)

#define	GPIO_MIC_BIAS_EN	EXYNOS4_GPE1(4)
#define	GPIO_SUB_MIC_BIAS_EN	EXYNOS4_GPE2(0)
#define	GPIO_EAR_MIC_BIAS_EN	EXYNOS4_GPE2(4)

#define	GPIO_TDMB_EN	EXYNOS4_GPC0(1)
#define	GPIO_TDMB_RST_N	EXYNOS4_GPB(5)
#define	GPIO_TDMB_INT	EXYNOS4_GPB(4)
#define	GPIO_TDMB_INT_AF	0xf

#define	GPIO_FM_RST	EXYNOS4_GPB(0)
#define	GPIO_FM_INT	EXYNOS4_GPB(1)
#define	GPIO_FM_INT_REV07	EXYNOS4_GPX2(4)
#define	GPIO_FM_SDA_28V	EXYNOS4_GPB(2)
#define	GPIO_FM_SCL_28V	EXYNOS4_GPB(3)

#endif /* __ASM_ARCH_GPIO_H */
