#include <linux/gpio.h>
#include <linux/serial_core.h>
#include <linux/io.h>
#include <plat/devs.h>
#include <plat/gpio-cfg.h>
#include <plat/regs-serial.h>
#include <plat/gpio-core.h>
#include <mach/gpio.h>



struct gpio_init_data {
	uint num;
	uint cfg;
	uint val;
	uint pud;
	uint drv;
};

static struct gpio_init_data c1_init_gpios[] = {
	{
		.num	= EXYNOS4_GPB(1),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
	 {
		.num	= EXYNOS4_GPB(5),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
	{
		.num	= EXYNOS4_GPC1(3),	/* CODEC_SDA_1.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPC1(4),	/* CODEC_SCL_1.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPD0(2),	/* MSENSOR_MHL_SDA_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPD0(3),	/* MSENSOR_MHL_SCL_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPD1(0),	/* 8M_CAM_SDA_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPD1(1),	/* 8M_CAM_SCL_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPD1(2),	/* SENSE_SDA_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPD1(3),	/* SENSE_SCL_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
	{
		.num	= EXYNOS4_GPK1(1),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV2,
	}, {
		.num	= EXYNOS4_GPK2(2),	/* PS_ALS_SDA_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
	{
		.num	= EXYNOS4_GPK3(1),	/* WLAN_SDIO_CMD */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPK3(2),	/* PS_ALS_SCL_2.8V */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPK3(3),	/* WLAN_SDIO_D(0) */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPK3(4),	/* WLAN_SDIO_D(1) */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPK3(5),	/* WLAN_SDIO_D(2) */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPK3(6),	/* WLAN_SDIO_D(3) */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPX0(1),	/* VOL_UP */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
	{
		.num	= EXYNOS4_GPX0(2),	/* VOL_DOWN */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPX0(3),	/* GPIO_BOOT_MODE */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		/* TODO: remove belows if max17042 would be ready */
		.num	= EXYNOS4_GPX2(3),	/* GPIO_FUEL_ALERT */
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPX3(1),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, /* {
		.num	= EXYNOS4_GPX3(2),	// GPIO_DET_35
		.cfg	= S3C_GPIO_SFN(GPIO_DET_35_AF),
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, */
	{
		.num	= EXYNOS4_GPX3(3),
		.cfg	= S3C_GPIO_OUTPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
	{
		.num	= EXYNOS4_GPX3(4),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 2,
		.pud	= S3C_GPIO_PULL_NONE,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
	{	/*GPY0 */
		.num	= EXYNOS4_GPY0(2),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY0(3),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY0(4),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY0(5),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
	{	/*GPY1 */
		.num	= EXYNOS4_GPY1(0),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY1(1),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
	{
		.num	= EXYNOS4_GPY1(2),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY1(3),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {	/*GPY2 */
		.num	= EXYNOS4_GPY2(0),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY2(1),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY2(2),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY2(3),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY2(4),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY2(5),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {	/*GPY4 */
		.num	= EXYNOS4_GPY4(4),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {	/*GPY5 */
		.num	= EXYNOS4_GPY5(0),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY5(1),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY5(2),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY5(3),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY5(4),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY5(5),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY5(6),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY5(7),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {	/* GPY6 */
		.num	= EXYNOS4_GPY6(0),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY6(1),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY6(2),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY6(3),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY6(4),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY6(5),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY6(6),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	}, {
		.num	= EXYNOS4_GPY6(7),
		.cfg	= S3C_GPIO_INPUT,
		.val	= 0,
		.pud	= S3C_GPIO_PULL_DOWN,
		.drv	= S5P_GPIO_DRVSTR_LV1,
	},
};

void c1_config_gpio_table(void)
{
	u32 i, gpio;

	printk(KERN_DEBUG "c1_config_gpio_table.\n");

	for (i = 0; i < ARRAY_SIZE(c1_init_gpios); i++) {
		gpio = c1_init_gpios[i].num;
		if (gpio <= EXYNOS4_MP02(5)) {
			s3c_gpio_cfgpin(gpio, c1_init_gpios[i].cfg);
			s3c_gpio_setpull(gpio, c1_init_gpios[i].pud);

			if (c1_init_gpios[i].val != 2)
				gpio_set_value(gpio, c1_init_gpios[i].val);

			s5p_gpio_set_drvstr(gpio, c1_init_gpios[i].drv);
		}
	}
}


/* this table only for c1 board */
static unsigned int c1_sleep_gpio_table[][3] = {
	{ EXYNOS4_GPA0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_UP},
	{ EXYNOS4_GPA0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPA0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPA0(3),  S3C_GPIO_SLP_OUT1,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPA0(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPA0(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPA0(6),	S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN}, /* NC */
	{ EXYNOS4_GPA0(7),	S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN}, /* NC */
	{ EXYNOS4_GPA1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPA1(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPA1(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPA1(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPA1(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPA1(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#if !defined(CONFIG_TDMB)
#if defined(CONFIG_TARGET_LOCALE_NTT)
	{ EXYNOS4_GPB(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPB(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPB(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPB(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPB(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPB(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#else
#if defined(CONFIG_TARGET_LOCALE_NAATT)
	{ EXYNOS4_GPB(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPB(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPB(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPB(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPB(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPB(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#else
	{ EXYNOS4_GPB(0),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPB(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPB(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPB(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPB(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPB(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
#endif
#else /* esper,2011-01-24 for KOR TDMB */
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPB(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPB(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPB(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPB(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPB(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPB(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
#endif
	{ EXYNOS4_GPB(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPB(7),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPC0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN}, /* REC_PCM_CLK */
#else
	{ EXYNOS4_GPC0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
#if defined(CONFIG_TDMB) /* esper,2011-01-24 for KOR TDMB */
	{ EXYNOS4_GPC0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#elif defined(CONFIG_ISDBT_FC8100)
	{ EXYNOS4_GPC0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#else
#ifndef CONFIG_MACH_C1_NA_SPR_REV05
	{ EXYNOS4_GPC0(1), S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
#endif
#endif
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPC0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN}, /* REC_PCM_SYNC */
#ifndef CONFIG_MACH_C1_NA_SPR_REV05
	{ EXYNOS4_GPC0(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN}, /* REC_PCM_IN */
#endif
	{ EXYNOS4_GPC0(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN}, /* REC_PCM_OUT */
#else
	{ EXYNOS4_GPC0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPC0(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPC0(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */

	{ EXYNOS4_GPC1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPC1(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPC1(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPC1(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPC1(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},

	{ EXYNOS4_GPD0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPD0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},	/* NC */
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPD0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPD0(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},

	{ EXYNOS4_GPD1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPD1(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPD1(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPD1(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},

	{ EXYNOS4_GPE0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPE0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPE0(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE0(4),  S3C_GPIO_SLP_OUT1,	S3C_GPIO_PULL_NONE},
	
	{ EXYNOS4_GPE1(0),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE1(1),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE1(2),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE1(3),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE1(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE1(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPE1(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPE1(7),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */

#if defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPE2(0),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
#else
	{ EXYNOS4_GPE2(0),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_DOWN},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPE2(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE2(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPE2(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPE2(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE2(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPE3(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(0) */
	{ EXYNOS4_GPE3(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(1) */
	{ EXYNOS4_GPE3(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(2) */
	{ EXYNOS4_GPE3(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(3) */
	{ EXYNOS4_GPE3(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(4) */
	{ EXYNOS4_GPE3(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(5) */
	{ EXYNOS4_GPE3(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(6) */
	{ EXYNOS4_GPE3(7),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(7) */

	{ EXYNOS4_GPE4(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(8) */
	{ EXYNOS4_GPE4(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(9) */
	{ EXYNOS4_GPE4(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(10) */
	{ EXYNOS4_GPE4(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(11) */
	{ EXYNOS4_GPE4(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(12) */
	{ EXYNOS4_GPE4(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(13) */
	{ EXYNOS4_GPE4(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(14) */
	{ EXYNOS4_GPE4(7),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* EBI2_AD(15) */
#else
	{ EXYNOS4_GPE3(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE3(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE3(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE3(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE3(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE3(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE3(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE3(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},

	{ EXYNOS4_GPE4(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE4(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE4(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE4(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE4(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE4(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE4(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPE4(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},

	{ EXYNOS4_GPF0(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF0(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF0(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF0(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF0(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF0(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF0(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},

	{ EXYNOS4_GPF1(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF1(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF1(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF1(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF1(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF1(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF1(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF1(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},

	{ EXYNOS4_GPF2(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF2(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF2(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF2(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF2(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF2(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF2(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF2(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},

	{ EXYNOS4_GPF3(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF3(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF3(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF3(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF3(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPF3(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPJ0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPJ0(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPJ0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPJ0(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPJ0(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPJ0(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPJ0(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPJ0(7),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */

	{ EXYNOS4_GPJ1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPJ1(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPJ1(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPJ1(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPJ1(4),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPK0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK0(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK0(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK0(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK0(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK0(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},

	{ EXYNOS4_GPK1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK1(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPK1(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK1(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK1(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK1(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK1(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},

	{ EXYNOS4_GPK2(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#if defined(CONFIG_MACH_C1_NA_SPR_REV05)
	{ EXYNOS4_GPK2(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE}, /* WIFI_CLK */
	{ EXYNOS4_GPK2(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE}, /* WIFI_CMD */
	{ EXYNOS4_GPK2(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE}, /* WIFI_D0 */
	{ EXYNOS4_GPK2(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPK2(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPK2(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#else
	{ EXYNOS4_GPK2(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK2(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK2(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK2(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK2(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPK2(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
#endif

#if defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPK3(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},  /* WIMAX_SDIO_CLK */
#else
	{ EXYNOS4_GPK3(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPK3(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPK3(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPK3(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPK3(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPK3(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPK3(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPL0(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPL0(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPL0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPL0(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPL0(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPL0(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPL0(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},  /* USB_SEL */
#else
	{ EXYNOS4_GPL0(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPL0(6),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPL0(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */

	{ EXYNOS4_GPL1(0),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPL1(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPL1(2),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},

	{ EXYNOS4_GPL2(0),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPL2(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#ifdef	CONFIG_MAX8922_CHARGER
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPL2(2),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
#else
	{ EXYNOS4_GPL2(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
	{ EXYNOS4_GPL2(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#ifdef	CONFIG_MAX8922_CHARGER
	{ EXYNOS4_GPL2(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPL2(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#else
	{ EXYNOS4_GPL2(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPL2(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
#if defined(CONFIG_TARGET_LOCALE_NTT)
	{ EXYNOS4_GPL2(6),	S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPL2(7),	S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
#else
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPL2(6),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPL2(7),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
#endif
#if defined(CONFIG_PN544) && defined(CONFIG_TARGET_LOCALE_KOR)
	{ EXYNOS4_GPL2(6),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPL2(7),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
#endif

#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPY0(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPY0(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
#endif /* CONFIG_TARGET_LOCALE_NA */
#ifndef CONFIG_MACH_C1_NA_SPR_REV05
	{ EXYNOS4_GPY0(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
	{ EXYNOS4_GPY0(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#ifndef CONFIG_MACH_C1_NA_SPR_REV05
	{ EXYNOS4_GPY0(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPY0(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
#if defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPY1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPY1(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
#else
	{ EXYNOS4_GPY1(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPY1(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPY1(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#ifndef CONFIG_MACH_C1_NA_SPR_REV05
	{ EXYNOS4_GPY1(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
#ifndef CONFIG_MACH_C1_NA_SPR_REV05
	{ EXYNOS4_GPY2(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPY2(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPY2(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
	{ EXYNOS4_GPY2(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPY2(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#ifndef CONFIG_MACH_C1_NA_SPR_REV05
	{ EXYNOS4_GPY2(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
#if defined(CONFIG_TARGET_LOCALE_NA)
	/* In Rev06, these pins are connected to always On LDOs */
	/* Assumes no effect in Rev03 and Rev05 boards */
	{ EXYNOS4_GPY3(0),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPY3(2),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_NONE},
#else
	{ EXYNOS4_GPY3(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},	/* MHL_SDA_1.8V */
	{ EXYNOS4_GPY3(1),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPY3(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},	/* MHL_SCL_1.8V */
	{ EXYNOS4_GPY3(3),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPY3(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPY3(5),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPY3(6),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPY3(7),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},

	{ EXYNOS4_GPY4(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPY4(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_NONE},
	/* GPIO_PDA_ACTIVE */
	{ EXYNOS4_GPY4(2),  S3C_GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE},
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPY4(3),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
#ifndef CONFIG_MACH_C1_NA_SPR_REV05
	{ EXYNOS4_GPY4(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},	/* NC */
#endif
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPY4(5),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	/* GPIO_CP_REQ_RESET */
	{ EXYNOS4_GPY4(6),  S3C_GPIO_SLP_OUT1,	S3C_GPIO_PULL_NONE},
	/* GPIO_UART_SEL */
	{ EXYNOS4_GPY4(7),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},

	{ EXYNOS4_GPY5(0),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPY5(1),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPY5(2),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPY5(3),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPY5(4),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPY5(5),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPY5(6),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},
	{ EXYNOS4_GPY5(7),  S3C_GPIO_SLP_INPUT,	S3C_GPIO_PULL_DOWN},

	{ EXYNOS4_GPY6(0),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPY6(1),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPY6(2),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPY6(3),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPY6(4),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPY6(5),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPY6(6),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPY6(7),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPZ(0),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPZ(1),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
#if !defined(CONFIG_TARGET_LOCALE_NA)
	{ EXYNOS4_GPZ(2),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPZ(3),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPZ(4),  S3C_GPIO_SLP_OUT0,  S3C_GPIO_PULL_NONE},
#endif /* CONFIG_TARGET_LOCALE_NA */
	{ EXYNOS4_GPZ(5),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	{ EXYNOS4_GPZ(6),  S3C_GPIO_SLP_INPUT, S3C_GPIO_PULL_DOWN},	/* NC */
	
#if defined(CONFIG_MACH_C1_NA_SPR_REV05)
	{ EXYNOS4_GPY2(5),  S3C_GPIO_SLP_OUT0,	S3C_GPIO_PULL_NONE}, /* SIDE_CLK_EN */
	{ EXYNOS4_GPC0(3),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_INT */
	{ EXYNOS4_GPY1(3),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_RST */
	{ EXYNOS4_GPY4(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_WAKEUP */
	{ EXYNOS4_GPY0(2),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_CS */
	{ EXYNOS4_GPY2(0),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_CLE */
	{ EXYNOS4_GPY2(1),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_ALE */
	{ EXYNOS4_GPY0(5),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_WE */
	{ EXYNOS4_GPY0(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_RE */
	{ EXYNOS4_GPY2(2),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_RB */
	{ EXYNOS4_GPY5(0),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_D0 */
	{ EXYNOS4_GPY5(1),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_D1 */
	{ EXYNOS4_GPY5(2),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPY5(3),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPY5(4),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPY5(5),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPY5(6),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE},
	{ EXYNOS4_GPY5(7),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* SIDE_D7 */
	{ EXYNOS4_GPC0(1),  S3C_GPIO_SLP_PREV,	S3C_GPIO_PULL_NONE}, /* AP_T_FLASH_DETECT */
#endif

};


extern int s3c_gpio_slp_cfgpin(unsigned int pin, unsigned int config);
extern int s3c_gpio_slp_setpull_updown(unsigned int pin, unsigned int config);

/* EXYNOS4 machine dependent GPIO help function */
int s3c_gpio_slp_cfgpin(unsigned int pin, unsigned int config)
{
	struct s3c_gpio_chip *chip = s3c_gpiolib_getchip(pin);
	void __iomem *reg;
	unsigned long flags;
	int offset;
	u32 con;
	int shift;

	if (!chip)
		return -EINVAL;

	if ((pin >= EXYNOS4_GPX0(0)) && (pin <= EXYNOS4_GPX3(7)))
		return -EINVAL;

	if (config > S3C_GPIO_SLP_PREV)
		return -EINVAL;

	reg = chip->base + 0x10;

	offset = pin - chip->chip.base;
	shift = offset * 2;

	local_irq_save(flags);

	con = __raw_readl(reg);
	con &= ~(3 << shift);
	con |= config << shift;
	__raw_writel(con, reg);

	local_irq_restore(flags);
	return 0;
}

s3c_gpio_pull_t s3c_gpio_get_slp_cfgpin(unsigned int pin)
{
	struct s3c_gpio_chip *chip = s3c_gpiolib_getchip(pin);
	void __iomem *reg;
	unsigned long flags;
	int offset;
	u32 con;
	int shift;

	if (!chip)
		return -EINVAL;

	if ((pin >= EXYNOS4_GPX0(0)) && (pin <= EXYNOS4_GPX3(7)))
		return -EINVAL;

	reg = chip->base + 0x10;

	offset = pin - chip->chip.base;
	shift = offset * 2;

	local_irq_save(flags);

	con = __raw_readl(reg);
	con >>= shift;
	con &= 0x3;

	local_irq_restore(flags);

	return (__force s3c_gpio_pull_t)con;
}

int s3c_gpio_slp_setpull_updown(unsigned int pin, unsigned int config)
{
	struct s3c_gpio_chip *chip = s3c_gpiolib_getchip(pin);
	void __iomem *reg;
	unsigned long flags;
	int offset;
	u32 con;
	int shift;

	if (!chip)
		return -EINVAL;

	if ((pin >= EXYNOS4_GPX0(0)) && (pin <= EXYNOS4_GPX3(7)))
		return -EINVAL;

	if (config > S3C_GPIO_PULL_UP)
		return -EINVAL;

	reg = chip->base + 0x14;

	offset = pin - chip->chip.base;
	shift = offset * 2;

	local_irq_save(flags);

	con = __raw_readl(reg);
	con &= ~(3 << shift);
	con |= config << shift;
	__raw_writel(con, reg);

	local_irq_restore(flags);

	return 0;
}

static void config_sleep_gpio_table(int array_size, unsigned int (*gpio_table)[3])
{
	u32 i, gpio;

	for (i = 0; i < array_size; i++) {
		gpio = gpio_table[i][0];
		s3c_gpio_slp_cfgpin(gpio, gpio_table[i][1]);
		s3c_gpio_slp_setpull_updown(gpio, gpio_table[i][2]);
	}
}

void c1_config_sleep_gpio_table(void)
{
/*
	[Fix Me] Below codes are sample GPIO initialization and review codes
	for target platform if needed.
*/
	config_sleep_gpio_table(ARRAY_SIZE(c1_sleep_gpio_table),
			c1_sleep_gpio_table);
}

s3c_config_sleep_gpio_table = c1_config_sleep_gpio_table;
